<a href="https://colab.research.google.com/github/Gvinay90/TensorFlow-2.0/blob/master/learn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Installing tensorflow through PIP

In [0]:
pip install tensorflow

In [0]:
import tensorflow as tf
import numpy as np
import datetime
from tensorflow.keras.datasets import fashion_mnist

In [0]:
tf.__version__

'2.2.0-rc3'

##Constant

###Defining Constant

In [0]:
tensor_20=tf.constant([[21,30],[10,20]])

In [0]:
tensor_20

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[21, 30],
       [10, 20]], dtype=int32)>

In [0]:
tensor_20.shape

TensorShape([2, 2])

###Getting the value of constant using nump

In [0]:
tensor_20.numpy()

array([[21, 30],
       [10, 20]], dtype=int32)

In [0]:
numpy_tensor=np.array([[21,30],[10,15]])

In [0]:
tensor_from_numpy

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[21, 30],
       [10, 15]])>

In [0]:
tensor_from_numpy=tf.constant(numpy_tensor)

In [0]:
tensor_20 + 2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[23, 32],
       [12, 22]], dtype=int32)>

##Variable


###Defning Variable


In [0]:
tf2_variables=tf.Variable([[1.,2.,3.],[4.,5.,6.]])
tf2_variables

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [0]:
tf2_variables[0,2].assign(100)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[  1.,   2., 100.],
       [  4.,   5.,   6.]], dtype=float32)>

In [0]:
tensor_example=tf.constant([[1,2],[3,4]])
tensor_example

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

###Performing Opereation on Constants

In [0]:
tensor_example +2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6]], dtype=int32)>

In [0]:
tensor_example * 2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 4],
       [6, 8]], dtype=int32)>

In [0]:
np.square(tensor_example)

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [0]:
np.sqrt(tensor_example)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

##String in TensorFLow

In [0]:
tf_string=tf.constant("TensorFlow")

In [0]:
tf_string

<tf.Tensor: shape=(), dtype=string, numpy=b'TensorFlow'>

In [0]:
tf_string.numpy()

b'TensorFlow'

In [0]:
tf.strings.length(tf_string)

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [0]:
tf.strings.unicode_decode(tf_string,"UTF-8")

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 84, 101, 110, 115, 111, 114,  70, 108, 111, 119], dtype=int32)>

In [0]:
tf_string_array=tf.constant(["TensroFlow","Machine Learning","Deep Learning","AI"])

In [0]:
tf_string_array.numpy()

array([b'TensroFlow', b'Machine Learning', b'Deep Learning', b'AI'],
      dtype=object)

In [0]:
with tf.device("/cpu:0"):
  tf_string_array=tf.constant(["TensroFlow","Machine Learning","Deep Learning","AI"])

In [0]:
tf_string.device

'/job:localhost/replica:0/task:0/device:CPU:0'

In [0]:
for i in tf_string_array.numpy():
  print(i)

b'TensroFlow'
b'Machine Learning'
b'Deep Learning'
b'AI'


In [0]:
for i in tf_string_array:
  print(i)

tf.Tensor(b'TensroFlow', shape=(), dtype=string)
tf.Tensor(b'Machine Learning', shape=(), dtype=string)
tf.Tensor(b'Deep Learning', shape=(), dtype=string)
tf.Tensor(b'AI', shape=(), dtype=string)


**Neural_Network**

In [0]:
(X_train, y_train), (X_test, y_test) = fashion_mnist.load_data()

In [0]:
X_train=X_train/255.0
X_test=X_test/255.0